os:
  - linux
  - osx

language: rust

rust:
  # No more support for 1.0 in pkg-config transitive build dependency
  # - 1.0.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
